etfs:
  IE00B4L5Y983:
    name: ISHARES CORE MSCI WORLD
    tickers:
    - IWDA
    exchange: NA
    figi: BBG000P71QK5
    resolved_at: '2026-08-11T00:34:06.955304'
    source: OpenFIGI
  IE00B5BMR087:
    name: ISHARES CORE S&P 500
    tickers:
    - CSSPX
    exchange: SW
    figi: BBG000Q362M9
    resolved_at: '2026-08-11T00:34:07.072684'
    source: OpenFIGI
  IE00BKM4GZ66:
    name: ISHARES CORE EM IMI ACC
    tickers:
    - EMIM
    exchange: LN
    figi: BBG006B70NW2
    resolved_at: '2026-08-11T00:34:07.201475'
    source: OpenFIGI
  LU1437018838:
    name: AM FTSE EPRA NRIT GL ETF ACC
    tickers:
    - EPRA
    exchange: FP
    figi: BBG00F2XZQ87
    resolved_at: '2026-08-11T18:59:40.714808'
    source: OpenFIGI
  LU1681048630:
    name: AM GLOBAL LUXURY ETF EUR ACC
    tickers:
    - GLUX
    exchange: FP
    figi: BBG00KVGM8F7
    resolved_at: '2026-08-11T18:59:40.929063'
    source: OpenFIGI
  IE00BM67HK77:
    name: X MSCI WORLD HEALTH CARE
    tickers:
    - XDWH
    exchange: GR
    figi: BBG00C9Y1409
    resolved_at: '2026-08-11T18:59:41.169708'
    source: OpenFIGI
  IE0006WW1TQ4:
    name: X MSCI WORLD EX USA 1C
    tickers:
    - EXUS
    exchange: GR
    figi: BBG01LMVXSR2
    resolved_at: '2026-08-11T18:59:41.284087'
    source: OpenFIGI
  IE00BDBRDM35:
    name: ISHARES GLB AGG EUR-H ACC
    tickers:
    - 0GGH
    exchange: LN
    figi: BBG00J5HL001
    resolved_at: '2026-08-11T19:01:52.629154'
    source: OpenFIGI
  IE0003XJA0J9:
    name: AMUNDI PRME ALL CTRY WLD ACC
    tickers:
    - WEBN
    exchange: GR
    figi: BBG01N504S06
    resolved_at: '2026-08-11T19:04:48.072491'
    source: OpenFIGI
  IE00B3VSSL01:
    name: INVESCO US TECHNOLOGY S&P
    tickers:
    - XLKS
    exchange: LN
    figi: BBG000Q2S7F4
    resolved_at: '2026-08-11T19:06:05.559603'
    source: OpenFIGI
  IE00B3YCGJ38:
    name: INVESCO S&P 500 ACC
    tickers:
    - SPXS
    exchange: LN
    figi: BBG000QXQZL9
    resolved_at: '2026-08-11T19:12:07.667661'
    source: OpenFIGI
  IE00B4K48X80:
    name: ISHARES CORE MSCI EUROPE ACC
    tickers:
    - IMAE
    exchange: NA
    figi: BBG000P71KS0
    resolved_at: '2026-08-11T19:13:16.082508'
    source: OpenFIGI
  IE00BM67HW99:
    name: X S&P 500 1C EUR
    tickers:
    - XDPE
    exchange: GR
    figi: BBG0083WJ3N6
    resolved_at: '2026-08-11T19:14:28.198579'
    source: OpenFIGI
  LU0908500753:
    name: AMUNDI CORE STOXX EUROPE 600
    tickers:
    - MEUDEUR
    exchange: XV
    figi: BBG0059HCCJ1
    resolved_at: '2026-08-11T19:15:28.786670'
    source: OpenFIGI
  IE000YYE6WK5:
    name: VANECK DEFENSE ETF
    tickers:
    - DFNS
    exchange: LN
    figi: BBG01G0CY1X0
    resolved_at: '2026-08-11T19:16:23.091200'
    source: OpenFIGI
  IE00B3WJKG14:
    name: ISHARES S&P 500 IT SECTOR
    tickers:
    - IUIT
    exchange: LN
    figi: BBG00BDQVD28
    resolved_at: '2026-08-11T19:18:10.128424'
    source: OpenFIGI
  IE00BFMXXD54:
    name: VANG S&P500 USDA
    tickers:
    - VUAA
    exchange: LN
    figi: BBG00P4FTPJ9
    resolved_at: '2026-08-11T23:19:24.676306'
    source: OpenFIGI
  FR0010510800:
    name: AMUND EURO OVERNIGHT RETURN
    tickers:
    - CSH1
    exchange: EO
    figi: BBG000JFGV18
    resolved_at: '2026-08-11T23:19:45.440946'
    source: OpenFIGI
  IE00B6R52259:
    name: ISHARES MSCI ACWI
    tickers:
    - ISAC
    exchange: LN
    figi: BBG00265DDD0
    resolved_at: '2026-08-11T23:19:45.584307'
    source: OpenFIGI
  IE00BHZPJ890:
    name: ISHARES MSCI USA ESG ENHANCE
    tickers:
    - EEDS
    exchange: LN
    figi: BBG00NJLSW92
    resolved_at: '2026-08-11T23:20:06.528416'
    source: OpenFIGI
  LU0290358497:
    name: X EUR OVERNIGHT RATE SWAP 1C
    tickers:
    - XEON
    exchange: GR
    figi: BBG000LYB7R4
    resolved_at: '2026-08-11T23:20:24.016499'
    source: OpenFIGI
  IE0031442068:
    name: ISHARES CORE S&P 500
    tickers:
    - IUSA
    exchange: LN
    figi: BBG000BMVZK4
    resolved_at: '2026-08-11T23:20:24.158835'
    source: OpenFIGI
  IE00B3F81R35:
    name: ISHARES CORE EURO CORP BOND
    tickers:
    - EUN5
    exchange: GR
    figi: BBG000C0HWG9
    resolved_at: '2026-08-11T23:20:34.605584'
    source: OpenFIGI
  IE00BF4RFH31:
    name: ISHARES MSCI WLD SMALL CAP
    tickers:
    - WSML
    exchange: LN
    figi: BBG00JSHKS97
    resolved_at: '2026-08-11T23:20:34.733063'
    source: OpenFIGI
  IE00B53SZB19:
    name: ISHARES NASDAQ 100 USD ACC
    tickers:
    - CSNDX
    exchange: SW
    figi: BBG000Q36BQ5
    resolved_at: '2026-08-11T23:21:12.023907'
    source: OpenFIGI
  IE00BK1PV551:
    name: X MSCI WORLD 1D
    tickers:
    - XDWL
    exchange: GR
    figi: BBG0083CHC16
    resolved_at: '2026-08-11T23:21:12.136746'
    source: OpenFIGI
  IE00BGSF1X88:
    name: ISHARES US TREAS 0-1YR USD A
    tickers:
    - IB01
    exchange: LN
    figi: BBG00NBPHQ05
    resolved_at: '2026-08-11T23:21:12.327214'
    source: OpenFIGI
  IE00B4WXJJ64:
    name: ISHARES CORE EURO GOVT BOND
    tickers:
    - SEGA
    exchange: LN
    figi: BBG000JTD0J0
    resolved_at: '2026-08-11T23:21:12.524138'
    source: OpenFIGI
  IE00BFY0GT14:
    name: SS SPDR MSCI WORLD UC-USD AC
    tickers:
    - SPPW
    exchange: GR
    figi: BBG00NG1CJQ6
    resolved_at: '2026-08-11T23:21:12.640351'
    source: OpenFIGI
  IE00BK5BQT80:
    name: VANG FTSE AW USDA
    tickers:
    - VWRA
    exchange: LN
    figi: BBG00PQQHQK0
    resolved_at: '2026-08-11T23:21:32.136999'
    source: OpenFIGI
  IE00B6YX5C33:
    name: SS SPDR S&P 500 UCIT ETF-UHG
    tickers:
    - SPY5
    exchange: GR
    figi: BBG002RR9FT2
    resolved_at: '2026-08-11T23:21:56.642318'
    source: OpenFIGI
